upstream backend {
    server backend:8000;
}

upstream frontend {
    server frontend:80;
}

server {
    listen 80;
    server_name vibenest-prakash.duckdns.org;

    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    server_name vibenest-prakash.duckdns.org;

    ssl_certificate /etc/letsencrypt/live/vibenest-prakash.duckdns.org/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/vibenest-prakash.duckdns.org/privkey.pem;

    location /api/v1/chat/ws {
        proxy_pass http://backend;

        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";

        proxy_set_header Host $host;
    }

    location /api/ {
        proxy_pass http://backend;

        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location / {
        proxy_pass http://frontend;
    }
}